export const main = { backgroundColor: '#ffffff', fontFamily: 'Arial, sans-serif', margin: 0, padding: 0, direction: 'rtl' as const, textAlign: 'right' as const }
export const container = { maxWidth: '600px', margin: '0 auto', padding: '20px', direction: 'rtl' as const, textAlign: 'right' as const }
export const heroBox = { background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)', padding: '32px 30px', borderRadius: '12px 12px 0 0', color: '#ffffff' }
export const heroTitle = { color: '#ffffff', margin: 0, fontSize: '22px', fontWeight: 600, textAlign: 'right' as const }
export const heroSub = { color: '#a0aec0', margin: '8px 0 0', fontSize: '14px', textAlign: 'right' as const }
export const card = { padding: '30px', border: '1px solid #e2e8f0', borderTop: 'none', direction: 'rtl' as const, textAlign: 'right' as const }
export const h1 = { color: '#1a1a2e', margin: '0 0 8px', fontSize: '20px', textAlign: 'right' as const }
export const text = { color: '#475569', fontSize: '15px', lineHeight: '1.7', margin: '0 0 16px', textAlign: 'right' as const }
export const muted = { color: '#94a3b8', fontSize: '13px', margin: '0 0 8px', textAlign: 'right' as const }
export const button = { display: 'inline-block', padding: '14px 40px', background: '#2563eb', color: '#ffffff', textDecoration: 'none', borderRadius: '10px', fontWeight: 700, fontSize: '16px' }
export const buttonWrap = { textAlign: 'center' as const, margin: '28px 0' }
export const footer = { background: '#f1f5f9', padding: '20px 30px', borderRadius: '0 0 12px 12px', border: '1px solid #e2e8f0', borderTop: 'none', textAlign: 'center' as const, fontSize: '12px', color: '#94a3b8' }
export const noteBox = { background: '#eff6ff', borderRight: '4px solid #3b82f6', padding: '16px 20px', margin: '0 0 20px', borderRadius: '0 8px 8px 0' }
export const docBox = { background: '#ffffff', padding: '14px 16px', borderRadius: '8px', marginBottom: '10px', border: '1px solid #e2e8f0', textAlign: 'right' as const, direction: 'rtl' as const }
export const docsWrap = { background: '#f8fafc', borderRadius: '10px', padding: '20px', marginBottom: '24px', textAlign: 'right' as const, direction: 'rtl' as const }